on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: '12'
      - name: Instala dependências
        run: npm install
      - name: Roda ESlint
        run: npx eslint